[project]
name = "finance-manager"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Chase McDonald", email = "1chasemcd@gmail.com" }
]
requires-python = ">=3.14"
dependencies = [
    "aiosqlite>=0.22.1",
    "fastapi[standard]>=0.141.1",
    "pydantic>=2.13.4",
    "sqlalchemy>=2.0.52",
]

[tool.ruff]
line-length = 100
target-version = "py314"

[tool.ruff.lint]
select = [
    "E",      # pycodestyle
    "F",      # pyflakes
    "I",      # import sorting
    "UP",     # pyupgrade
    "B",      # flake8-bugbear
    "SIM",    # flake8-simplify
    "ANN",    # annotations
]
ignore = [
    "ANN401", # dynamically typed Any
]

[tool.ruff.format]
quote-style = "double"

[tool.pyright]
include = ["src"]
typeCheckingMode = "strict"
pythonVersion = "3.14"
strict = ["src"]

[tool.uv]
package = true

[tool.fastapi]
entrypoint = "finance_manager.main:app"

[build-system]
requires = ["uv_build>=0.12.5,<0.13.0"]
build-backend = "uv_build"

[dependency-groups]
dev = [
    "pyright>=1.1.411",
    "pytest>=9.1.1",
    "ruff>=0.16.4",
]
